[build]
  command = "npm run build:static"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [functions]
  directory = "netlify/functions"
