[build]
  command = "npm run build:static"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

# Tell Netlify how to run and proxy the DEV server during the Visual Editor preview
[dev]
  framework = "vite"       # let Netlify manage a Vite dev server
  command = "vite"         # long-running dev command (NOT a build)
  targetPort = 5173        # Vite's port
  port = 8888              # Netlify will expose the preview on this port

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [functions]
  directory = "netlify/functions"
