[build]
  command = "npm run build:static"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

# Tell Netlify how to run and proxy the DEV server during the Visual Editor preview
[dev]
  command = "vite"         # or "npm run dev:vite" if vite is not installed globally
  targetPort = 5173        # Vite's port from vite.config.ts
  port = 8888              # Port Netlify will expose for the preview
  autoLaunch = false       # Prevent auto-opening the browser in the build container

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

