import { createContext, useContext } from "react";

export type Language = "en" | "hr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translation dictionaries
export const translations = {
  en: {
    // Navigation
    "nav.services": "Services",
    "nav.about": "About",
    "nav.testimonials": "Testimonials", 
    "nav.pricing": "Pricing",
    "nav.resources": "Resources",
    "nav.blog": "Blog",
    "nav.contact": "Contact",
    "nav.student_app": "Student App",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.home": "Home",
    
    // Hero Section
    "hero.title": "Master Mathematics with Personalized Online Tutoring",
    "hero.subtitle": "Expert one-on-one math tutoring from Middle School to University level. Build confidence, improve grades, and achieve your academic goals.",
    "hero.cta_primary": "Book Free Trial Session",
    "hero.cta_secondary": "Learn More About Services",
    "hero.trial_duration": "15-minute free trial",
    
    // Services Section
    "services.title": "Math Tutoring Services",
    "services.subtitle": "Comprehensive support for every level of mathematics",
    "services.middle_school": "Middle School Math",
    "services.middle_desc": "Basic algebra, fractions, and foundational problem-solving",
    "services.middle_tagline": "Start strong with the basics",
    "services.high_school": "High School Math",
    "services.high_desc": "Algebra, geometry, trigonometry, and pre-calculus", 
    "services.high_tagline": "Master advanced concepts",
    "services.university": "University Math",
    "services.university_desc": "Statistics and linear algebra for college success",
    "services.university_tagline": "Excel in higher mathematics",
    "services.sat_act": "SAT/ACT Math Bootcamp",
    "services.sat_desc": "Test strategies and practice for your best score",
    "services.sat_tagline": "Most Popular",
    "services.per_hour": "per hour",
    "services.book_now": "Book Now",
    
    // About Section
    "about.title": "About Luka",
    "about.subtitle": "Passionate educator with 5+ years of tutoring experience",
    "about.description": "Hi! I'm Luka, a dedicated math tutor with a passion for helping students overcome their math challenges and build lasting confidence. My personalized approach focuses on understanding each student's unique learning style and adapting my teaching methods accordingly.",
    "about.experience": "5+ Years Experience",
    "about.students": "200+ Happy Students",
    "about.success_rate": "95% Success Rate",
    
    // Testimonials
    "testimonials.title": "What Students Say",
    "testimonials.subtitle": "Real feedback from students who've achieved their math goals",
    
    // Pricing
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle": "Choose the plan that works for your learning goals",
    "pricing.per_session": "per session",
    "pricing.most_popular": "Most Popular",
    "pricing.get_started": "Get Started",
    
    // Resources
    "resources.title": "Free Math Resources",
    "resources.subtitle": "Study guides, practice problems, and helpful tips",
    "resources.algebra_title": "Algebra Quick Reference",
    "resources.algebra_desc": "Essential formulas and concepts for algebra success",
    "resources.geometry_title": "Geometry Cheat Sheet",
    "resources.geometry_desc": "Area, perimeter, and volume formulas made simple",
    "resources.sat_title": "SAT Math Strategy", 
    "resources.sat_desc": "Test-taking strategies to maximize your score",
    "resources.download_pdf": "Download PDF",
    
    // Blog
    "blog.title": "Latest Math Insights",
    "blog.subtitle": "Expert tips, study strategies, and math concepts explained simply",
    "blog.view_all": "View All Articles",
    "blog.read_more": "Read More",
    
    // Contact
    "contact.title": "Ready to Start Learning?",
    "contact.subtitle": "Book your free trial session and see the difference personalized tutoring makes",
    "contact.form_title": "Book Your Free Trial",
    "contact.full_name": "Full Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.math_level": "Math Level",
    "contact.goals": "Tell me about your math goals",
    "contact.goals_placeholder": "What specific topics do you need help with? What are your goals?",
    "contact.submit": "Book My Free Trial Session",
    "contact.response_time": "I'll respond within 24 hours to schedule your session",
    "contact.lets_connect": "Let's Connect",
    "contact.email_label": "Email",
    "contact.phone_label": "Phone", 
    "contact.hours": "Available Hours (CET)",
    "contact.schedule": "Mon-Fri: 3pm-9pm\nSat-Sun: 10am-6pm",
    
    // Math Levels
    "level.middle_school": "Middle School Math (Grades 6-8)",
    "level.high_school": "High School Math (Grades 9-12)", 
    "level.university": "Sveučilišna matematika",
    "level.sat_act": "SAT/ACT Prep (Test Preparation)",
    
    // Why Choose
    "why.title": "Why Choose LukaMath?",
    "why.personalized": "Personalized learning approach",
    "why.proven": "Proven track record of success", 
    "why.flexible": "Flexible scheduling options",
    "why.guarantee": "100% satisfaction guarantee",
    
    // Certificates
    "certificates.title": "Credentials and Certifications",
    "certificates.subtitle": "Continuous learning to provide the best math education",
    "cert.math_data_science": "Math for Data Science",
    "cert.math_data_science_desc": "Statistical foundations and mathematical modeling",
    "cert.master_data_science": "Master of Data Science",
    "cert.master_data_science_desc": "Advanced analytics and machine learning",
    "cert.virtual_teaching": "Virtual Teaching Specialization",
    "cert.virtual_teaching_desc": "Online pedagogy and instructional design",
    "cert.data_analytics": "Data Analytics Certificate",
    "cert.data_analytics_desc": "Business intelligence and data visualization",
    "cert.data_science_math": "Data Science Math Skills",
    "cert.data_science_math_desc": "Mathematical foundations for data science",
    
    // Footer
    "footer.description": "Helping students build confidence and achieve success in mathematics through personalized, one-on-one tutoring.",
    "footer.quick_links": "Quick Links",
    "footer.contact": "Contact",
    "footer.copyright": "© 2024 LukaMath. All rights reserved. | Privacy Policy | Terms of Service",
    "footer.available": "Available 7 days a week",
    
    // Success Modal
    "success.title": "Message Sent!",
    "success.message": "Thank you for your interest! I'll get back to you within 24 hours to schedule your free trial session.",
    
    // Authentication
    "auth.login": "Login",
    "auth.register": "Register",
    "auth.logout": "Logout",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirm_password": "Confirm Password",
    "auth.first_name": "First Name",
    "auth.last_name": "Last Name",
    "auth.login_button": "Log In",
    "auth.register_button": "Create Account",
    "auth.forgot_password": "Forgot Password?",
    "auth.have_account": "Already have an account?",
    "auth.no_account": "Don't have an account?",
    "auth.sign_in_here": "Sign in here",
    "auth.create_account_here": "Create one here",
    "auth.email_exists": "An account with this email already exists",
    "auth.registration_failed": "Registration failed. Please try again.",
    "auth.registration_success": "Account created successfully! Welcome to LukaMath.",
    "auth.login_success": "Welcome back!",
    "auth.invalid_credentials": "Invalid email or password",
    "auth.server_error": "Server error. Please try again later.",
    "auth.validation_failed": "Please check your input",
    "auth.token_required": "Authentication required",
    "auth.token_invalid": "Session expired. Please log in again.",
    "auth.not_authenticated": "Please log in to continue",
    "auth.user_not_found": "User not found",
    "auth.user_retrieved": "User information loaded",
    "auth.logout_success": "Logged out successfully",
    "auth.token_valid": "Session is valid",
    "auth.authentication_required": "Please log in to access this feature",
    "auth.insufficient_permissions": "You don't have permission to access this feature",
    "auth.password_requirements": "Password must contain uppercase, lowercase, number and special character",

    // Student App Extended
    "app.questions_answers": "Questions & Answers",
    "app.no_questions_yet": "No questions yet",
    "app.ask_first_question_desc": "Start by asking your first question to get personalized help",
    "app.ask_first_question": "Ask Your First Question",
    "app.answered": "Answered",
    "app.asked_on": "Asked on",
    "app.subject": "Subject",
    "app.question_placeholder": "Brief description of your question",
    "app.content_placeholder": "Describe your question in detail here...",
    "app.cancel": "Cancel",
    "app.submit_question_btn": "Submit Question",
    "app.pwa_app": "PWA App",
    "app.open": "Open",
    "app.home": "Home",
    "app.your_progress": "Your Progress",
    "app.homework_statistics": "Homework Statistics",
    "app.total_assignments": "Total Assignments",
    "app.completed_count": "Completed",
    "app.in_progress": "In Progress",
    "app.pending_count": "Pending",
    "app.qa_activity": "Q&A Activity",
    "app.total_questions": "Total Questions",
    "app.answered_count": "Answered",
    "app.unanswered": "Unanswered",
    "app.progress_chart": "Progress Chart",
    "app.assignment_number": "Assignment #",
    "app.grade_label": "Grade",
    "app.no_progress_data": "No progress data available",
    "app.schedule_session": "Schedule a Session",
    "app.schedule_session_desc": "Choose a time when you'd like to have a session with Luka",
    "app.book_session_btn": "Book Session",
    "app.no_homework_yet": "No homework yet",
    "app.tutor_will_assign": "Your tutor will assign homework that will appear here.",
    "app.terms": "Schedule",
    "app.student_app_title": "Student App",
    "app.track_manage": "Track your progress, submit homework, and ask questions.",
    "app.in_progress_status": "in progress",
    "app.homework_status": "Homework Status",
    "app.your_question": "Your Question",
    "app.answer": "Answer",
    "app.answered_on_date": "Answered on",
    "app.question_title_label": "Question Title",
    "app.question_details_label": "Question Details",

    // Common
    "common.sending": "Sending...",
    "common.loading": "Loading...",
    "common.required": "required"
  },
  hr: {
    // Navigation
    "nav.services": "Usluge",
    "nav.about": "O meni",
    "nav.testimonials": "Mišljenja", 
    "nav.pricing": "Cjenik",
    "nav.resources": "Materijali",
    "nav.blog": "Blog",
    "nav.contact": "Kontakt",
    "nav.student_app": "Aplikacija",
    "nav.login": "Prijava",
    "nav.logout": "Odjava",
    "nav.home": "Početna",
    
    // Hero Section
    "hero.title": "Savladajte matematiku —",
    "hero.title_highlight": "uz personalizirano podučavanje",
    "hero.subtitle": "Stručno individualno podučavanje matematike od osnovne do sveučilišne razine. Izgradite samopouzdanje, poboljšajte ocjene i postignite svoje ciljeve.",
    "hero.cta_primary": "Rezerviraj probni sat (15min)",
    "hero.cta_secondary": "Istraži našu aplikaciju",
    "hero.trial_duration": "15-minutni besplatni probni sat",
    
    // Services Section
    "services.title": "Usluge podučavanja matematike",
    "services.subtitle": "Sveobuhvatna podrška za sve razine matematike",
    "services.middle_school": "Matematika za osnovnu školu",
    "services.middle_desc": "Osnove algebre, razlomci i temelji rješavanja problema",
    "services.middle_tagline": "Počni snažno s osnovama",
    "services.high_school": "Matematika za srednju školu",
    "services.high_desc": "Algebra, geometrija, trigonometrija i funkcije", 
    "services.high_tagline": "Svladaj napredne koncepte",
    "services.university": "Sveučilišna matematika",
    "services.university_desc": "Statistika i linearna algebra za sveučilišni uspjeh",
    "services.university_tagline": "Postani izvrsna/n u višoj matematici",
    "services.sat_act": "Državna matura - matematika",
    "services.sat_desc": "Strategije testiranja i vježba za tvoj najbolji rezultat",
    "services.sat_tagline": "Najpopularnije",
    "services.most_popular": "Najpopularnije",
    "services.per_hour": "po satu",
    "services.book_now": "Rezerviraj",
    
    // Certificates
    "certificates.title": "Uvjerenja i certifikati",
    "certificates.subtitle": "Kontinuirano učenje za pružanje najbolje matematičke edukacije",
    
    // About Section
    "about.title": "Upoznajte svog mentora za matematiku",
    "about.subtitle": "Strastveni edukator s više od 5 godina iskustva u podučavanju",
    "about.description": "Ja sam Luka, i već više od 5 godina pomažem učenicima da svladaju strah od matematike. S diplomom iz Data Science u tijeku i strašću za podučavanjem, specijaliziram se za pretvaranje složenih koncepata u jednostavne.",
    "about.experience": "Više od 5 godina iskustva u podučavanju",
    "about.education": "Diploma iz Data Science na vrhunskom sveučilištu",
    "about.specialization": "Specijaliziran za pripremu testova",
    
    // Testimonials
    "testimonials.title": "Što učenici kažu",
    "testimonials.subtitle": "Prava povratna informacija učenika koji su postigli svoje matematičke ciljeve",
    
    // Pricing
    "pricing.title": "Jednostavan i transparentan cjenik",
    "pricing.subtitle": "Prvo odaberite svoju razinu matematike kako biste vidjeli odgovarajuće cijene",
    "pricing.select_level": "Odaberite svoju razinu matematike",
    "pricing.per_session": "po terminu",
    "pricing.most_popular": "Najpopularnije",
    "pricing.get_started": "Počni",
    "pricing.packages": "paketi",
    "pricing.choose_package": "Odaberite paket koji odgovara vašim ciljevima učenja",
    "pricing.single_session": "Pojedinačni sat",
    "pricing.hour": "sat",
    "pricing.hr": "h",
    "pricing.one_on_one": "Poduka jedan na jedan",
    "pricing.personalized_plan": "Personalizirani plan nastave",
    "pricing.practice_materials": "Materijali za vježbanje",
    "pricing.progress_tracking": "Praćenje napretka",
    "pricing.book_session": "Rezerviraj sat",
    "pricing.four_session_package": "Paket od 4 sata",
    "pricing.four_sessions": "Četiri termina od sat vremena (iskoristiti u roku od 1 mjeseca)",
    "pricing.save": "Uštedite",
    "pricing.total": "ukupno",
    "pricing.structured_path": "Strukturirani put učenja",
    "pricing.weekly_reviews": "Tjedni pregledi napretka",
    "pricing.priority_scheduling": "Prioritetno raspoređivanje",
    "pricing.start_package": "Počni paket",
    "pricing.eight_session_intensive": "Intenzivni program od 8 sati",
    "pricing.eight_sessions": "Osam termina od sat vremena (iskoristiti u roku od 2 mjeseca)",
    "pricing.comprehensive_curriculum": "Sveobuhvatan nastavni plan",
    "pricing.progress_assessments": "Procjene napretka",
    "pricing.flexible_scheduling": "Fleksibilno raspoređivanje",
    "pricing.start_intensive": "Počni intenzivni program",
    "pricing.guarantee": "100% jamstvo zadovoljstva • 15-minutni besplatni probni sat",
    
    // Resources
    "resources.title": "Besplatni matematički materijali",
    "resources.subtitle": "Priručnici za učenje, zadaci za vježbu i korisni savjeti",
    "resources.algebra_title": "Brzi priručnik za algebru",
    "resources.algebra_desc": "Ključne formule i koncepti za uspjeh u algebri",
    "resources.geometry_title": "Geometrijski priručnik",
    "resources.geometry_desc": "Formule za površinu, opseg i volumen jednostavno objašnjene",
    "resources.sat_title": "Državna matura - strategija", 
    "resources.sat_desc": "Strategije pristupa testu za maksimizaciju rezultata",
    "resources.download_pdf": "Preuzmi PDF",
    
    // Certificates  
    "cert.math_data_science": "Matematika za znanost o podacima",
    "cert.math_data_science_desc": "Statističke osnove i matematičko modeliranje",
    "cert.master_data_science": "Znanost o podacima", 
    "cert.master_data_science_desc": "Napredna analitika i strojno učenje",
    "cert.virtual_teaching": "Specijalizacija virtualnog poučavanja",
    "cert.virtual_teaching_desc": "Online pedagogija i dizajn nastave",
    "cert.data_analytics": "Certifikat za analitiku podataka",
    "cert.data_analytics_desc": "Poslovna inteligencija i vizualizacija podataka",
    "cert.data_science_math": "Matematičke vještine za znanost o podacima",
    "cert.data_science_math_desc": "Matematičke osnove za znanost o podacima",
    
    // Blog
    "blog.title": "Najnoviji matematički uvidi",
    "blog.subtitle": "Stručni savjeti, strategije učenja i matematički koncepti jednostavno objašnjeni",
    "blog.view_all": "Pogledaj sve članke",
    "blog.read_more": "Čitaj više",
    "blog.featured_articles": "Istaknuti članci",
    "blog.all_articles": "Svi članci",
    
    // Contact
    "contact.title": "Spreman si početi učiti?",
    "contact.subtitle": "Rezerviraj svoj 15-minutni besplatni probni sat i vidi razliku koju čini personalizirano podučavanje",
    "contact.form_title": "Rezerviraj svoj 15-minutni besplatni probni sat",
    "contact.full_name": "Puno ime",
    "contact.email": "Email adresa",
    "contact.phone": "Broj telefona",
    "contact.math_level": "Razina matematike",
    "contact.goals": "Opišite mi svoje matematičke ciljeve",
    "contact.goals_placeholder": "S kojim specifičnim temama trebate pomoć? Koji su vaši ciljevi?",
    "contact.submit": "Rezerviraj moj probni sat (15min)",
    "contact.response_time": "Odgovorit ću u roku od 24 sata za dogovaranje termina",
    "contact.lets_connect": "Povežimo se",
    "contact.email_label": "Email",
    "contact.phone_label": "Telefon", 
    "contact.hours": "Dostupni sati (CET)",
    "contact.schedule": "Pon-Pet: 15-21h\nSub-Ned: 10-18h",
    
    // Math Levels
    "level.middle_school": "Matematika za osnovnu školu (5.-8. razred)",
    "level.high_school": "Matematika za srednju školu (1.-4. razred)", 
    "level.statistics": "Statistika",
    "level.linear_algebra": "Linearna algebra",
    "level.sat_act": "Državna matura (priprema za testove)",
    "level.middle_school_desc": "Osnove i temeljne vještine za uspjeh u srednjoj školi",
    "level.high_school_desc": "Napredni koncepti i priprema za fakultet", 
    "level.university_desc": "Napredna statistika i linearna algebra",
    "level.linear_algebra_desc": "Matrice, vektori i linearne transformacije",
    "level.sat_act_desc": "Strategije testova i vježba za najbolji rezultat na Državnoj maturi",
    
    // Why Choose
    "why.title": "Zašto odabrati LukaMath?",
    "why.personalized": "Personalizirani pristup učenju",
    "why.proven": "Dokazana stopa uspjeha", 
    "why.flexible": "Fleksibilne opcije raspoređivanja",
    "why.guarantee": "100% jamstvo zadovoljstva",
    
    // Footer
    "footer.description": "Pomažem učenicima u izgradnji samopouzdanja i postizanju uspjeha u matematici kroz personalizirano individualno podučavanje.",
    "footer.quick_links": "Brze veze",
    "footer.contact": "Kontakt",
    "footer.copyright": "© 2025 LukaMath. Sva prava zadržana. | Pravila privatnosti | Uvjeti korištenja",
    "footer.available": "Dostupan 7 dana u tjednu",
    
    // Success Modal
    "success.title": "Poruka je poslana!",
    "success.message": "Hvala na interesu! Odgovorit ću u roku od 24 sata za dogovaranje vašeg 15-minutnog besplatnog probnog sata.",
    
    // App Features Page
    "app_features.title": "Studentska aplikacija LukaMath",
    "app_features.subtitle": "Sve što trebate za uspjeh u matematici na jednom mjestu",
    "app_features.homework_title": "Upravljanje domaćom zadaćom",
    "app_features.homework_desc": "Primajte zadatke od Luke, pratite krajnje rokove i predajte završene radove - sve na jednom mjestu",
    "app_features.qa_title": "Direktno pitanje Luki",
    "app_features.qa_desc": "Pitajte Luku bilo kada i dobijte detaljno objašnjenje za bilo koji matematički zadatak",
    "app_features.progress_title": "Praćenje napretka",
    "app_features.progress_desc": "Vizualni grafovi koji prikazuju vaše poboljšanje u različitim matematičkim temama i zadacima",
    "app_features.calendar_title": "Kalendar dostupnosti",
    "app_features.calendar_desc": "Provjerite Lukinu dostupnost i zakazujte termine podučavanja u pogodnim terminima",
    "app_features.feedback_title": "Povratne informacije i ocjenjivanje",
    "app_features.feedback_desc": "Primajte detaljne povratne informacije o vašoj domaćoj zadaći s ocjenama i prijedlozima za poboljšanje",
    "app_features.timeline_title": "Vremenska crta zadataka",
    "app_features.timeline_desc": "Jasna pregled nadolazećih rokova, završenih radova i čekajućih zadataka",
    "app_features.get_started": "Registrirajte se besplatno",
    "app_features.learn_more": "Saznaj više",
    "app_features.features_title": "Sve što trebate da ostanete organizirani",
    "app_features.features_subtitle": "Vaš osobni sustav za upravljanje domaćom zadaćom dizajniran da vas drži na pravom putu sa zadacima, pitanjima i napretkom uz vašeg osobnog nastavnika.",
    "app_features.how_it_works_title": "Kako LukaMath aplikacija funkcionira",
    "app_features.how_it_works_subtitle": "Jednostavni koraci za transformaciju vašeg iskustva učenja matematike",
    "app_features.step1_title": "Stvorite svoj račun",
    "app_features.step1_desc": "Registrirajte se besplatno i dobijte pristup svojoj osobnoj aplikaciji za upravljanje domaćom zadaćom s Lukom kao vašim nastavnikom.",
    "app_features.step2_title": "Primajte zadatke",
    "app_features.step2_desc": "Dobijte domaću zadaću od Luke, pratite rokove, postavite pitanja i predajte svoj završeni rad.",
    "app_features.step3_title": "Zakazivanje i napredak",
    "app_features.step3_desc": "Provjerite Lukinu dostupnost za termine, pratite svoje ocjene i nadgledajte svoje poboljšanje kroz vrijeme.",
    "app_features.cta_title": "Jeste li spremni zakoračiti u novi svijet matematike?",
    "app_features.cta_desc": "Pridružite se učenicima koji vladaju svojim zadacima i poboljšavaju svoje matematičke vještine uz posvećeni sustav za upravljanje domaćom zadaćom.",

    // PWA
    "pwa.install_app": "Instalirajte našu aplikaciju",
    "pwa.homework": "domaća zadaća",

    // Register Page
    "register.title": "Registracija na LukaMath",
    "register.subtitle": "Pridružite se stotinama učenika koji su poboljšali svoje matematičke vještine",
    "register.first_name": "Ime",
    "register.last_name": "Prezime",
    "register.email": "Email adresa",
    "register.language": "Preferirani jezik",
    "register.language_en": "Engleski",
    "register.language_hr": "Hrvatski",
    "register.math_level": "Trenutna razina matematike",
    "register.parent_email": "Email roditelja (opcionalno)",
    "register.goals": "Vaši ciljevi u matematici",
    "register.goals_placeholder": "Opišite što želite postići u matematici...",
    "register.submit": "Registriraj se",
    "register.success_title": "Registracija uspješna!",
    "register.success_message": "Dobrodošli u LukaMath! Molimo provjerite svoj email za sljedeće korake.",
    "register.back_home": "Povratak na početnu",

    // Student App
    "app.homework": "Domaća zadaća",
    "app.questions": "Pitanja",
    "app.progress": "Napredak",
    "app.calendar": "Kalendar",
    "app.welcome": "Dobrodošli,",
    "app.homework_empty": "Trenutno nemate dodijeljene domaće zadaće",
    "app.questions_empty": "Nemate postavljenih pitanja",
    "app.ask_question": "Postavi pitanje",
    "app.question_title": "Naslov pitanja",
    "app.question_content": "Vaše pitanje",
    "app.submit_question": "Pošalji pitanje",
    "app.due_date": "Krajnji rok",
    "app.completed": "Završeno",
    "app.pending": "U tijeku",
    "app.overdue": "Prekršen rok",
    "app.grade": "Ocjena",
    "app.feedback": "Povratne informacije",
    "app.download": "Preuzmi",
    "app.no_availability": "Nema dostupnih termina",
    "app.book_session": "Rezerviraj sesiju",
    "app.logout": "Odjava",

    // Blog Page
    "blog.page_title": "LukaMath Blog",
    "blog.page_subtitle": "Matematički savjeti, strategije i uvidi",
    "blog.featured": "Istaknuto",
    "blog.search_placeholder": "Pretražite članke...",
    "blog.all_categories": "Sve kategorije",
    "blog.test_prep": "Priprema za testove",
    "blog.algebra": "Algebra",
    "blog.geometry": "Geometrija",
    "blog.calculus": "Kalkulus",
    "blog.study_skills": "Vještine učenja",
    "blog.back_to_home": "Povratak na početnu",

    // Authentication
    "auth.login": "Prijava",
    "auth.register": "Registracija",
    "auth.logout": "Odjava",
    "auth.email": "Email",
    "auth.password": "Lozinka",
    "auth.confirm_password": "Potvrdi lozinku",
    "auth.first_name": "Ime",
    "auth.last_name": "Prezime",
    "auth.login_button": "Prijaviť se",
    "auth.register_button": "Stvori račun",
    "auth.forgot_password": "Zaboravili ste lozinku?",
    "auth.have_account": "Već imate račun?",
    "auth.no_account": "Nemate račun?",
    "auth.sign_in_here": "Prijavite se ovdje",
    "auth.create_account_here": "Stvorite ga ovdje",
    "auth.email_exists": "Račun s ovom email adresom već postoji",
    "auth.registration_failed": "Registracija neuspješna. Molimo pokušajte ponovno.",
    "auth.registration_success": "Račun uspješno stvoren! Dobrodošli u LukaMath.",
    "auth.login_success": "Dobrodošli natrag!",
    "auth.invalid_credentials": "Neispravna email adresa ili lozinka",
    "auth.server_error": "Greška servera. Molimo pokušajte ponovno kasnije.",
    "auth.validation_failed": "Molimo provjerite vaš unos",
    "auth.token_required": "Potrebna je autentifikacija",
    "auth.token_invalid": "Sesija je istekla. Molimo prijavite se ponovno.",
    "auth.not_authenticated": "Molimo prijavite se za nastavak",
    "auth.user_not_found": "Korisnik nije pronađen",
    "auth.user_retrieved": "Korisničke informacije učitane",
    "auth.logout_success": "Uspješno ste se odjavili",
    "auth.token_valid": "Sesija je važeća",
    "auth.authentication_required": "Molimo prijavite se za pristup ovoj značajci",
    "auth.insufficient_permissions": "Nemate dozvolu za pristup ovoj značajci",
    "auth.password_requirements": "Lozinka mora sadržavati velika i mala slova, broj i poseban znak",

    // Student App Extended
    "app.questions_answers": "Pitanja i odgovori",
    "app.no_questions_yet": "Još nema pitanja",
    "app.ask_first_question_desc": "Počnite postavljanjem prvog pitanja za personaliziranu pomoć",
    "app.ask_first_question": "Postavite prvo pitanje",
    "app.answered": "Odgovoreno",
    "app.asked_on": "Postavljeno",
    "app.subject": "Predmet",
    "app.question_placeholder": "Kratki opis vašeg pitanja",
    "app.content_placeholder": "Detaljno opišite vaše pitanje ovdje...",
    "app.cancel": "Odustani",
    "app.submit_question_btn": "Pošalji pitanje",
    "app.pwa_app": "PWA aplikacija",
    "app.open": "Otvori",
    "app.home": "Početna",
    "app.your_progress": "Vaš napredak",
    "app.homework_statistics": "Statistika domaće zadaće",
    "app.total_assignments": "Ukupno zadataka",
    "app.completed_count": "Završeno",
    "app.in_progress": "U tijeku",
    "app.pending_count": "Na čekanju",
    "app.qa_activity": "Q&A aktivnost",
    "app.total_questions": "Ukupno pitanja",
    "app.answered_count": "Odgovoreno",
    "app.unanswered": "Neodgovoreno",
    "app.progress_chart": "Grafikon napretka",
    "app.assignment_number": "Zadatak br.",
    "app.grade_label": "Ocjena",
    "app.no_progress_data": "Nema podataka o napretku",
    "app.schedule_session": "Zakaži sesiju",
    "app.schedule_session_desc": "Odaberite vrijeme kada biste željeli imati sesiju s Lukom",
    "app.book_session_btn": "Rezerviraj sesiju",
    "app.no_homework_yet": "Još nemate domaću zadaću",
    "app.tutor_will_assign": "Vaš tutor će dodijeliti domaću zadaću koja će se pojaviti ovdje.",
    "app.terms": "Termini",
    "app.student_app_title": "Studentska aplikacija",
    "app.track_manage": "Pratite svoj napredak, predajte domaću zadaću i postavite pitanja.",
    "app.in_progress_status": "u tijeku",
    "app.homework_status": "Status domaće zadaće",
    "app.your_question": "Vaše pitanje",
    "app.answer": "Odgovor",
    "app.answered_on_date": "Odgovoreno",
    "app.question_title_label": "Naslov pitanja",
    "app.question_details_label": "Detalji pitanja",

    // Common
    "common.sending": "Šalje se...",
    "common.loading": "Učitava...",
    "common.required": "obavezno",
    "common.save": "Spremi",
    "common.cancel": "Odustani",
    "common.edit": "Uredi",
    "common.delete": "Obriši",
    "common.confirm": "Potvrdi",
    "common.yes": "Da",
    "common.no": "Ne"
  }
};
