backend:
  name: github
  repo: lukadmi/lukamath
  branch: main
  base_url: /.netlify/functions
  auth_endpoint: auth

media_folder: "client/public/uploads"   # files will be committed here
public_folder: "/uploads"               # how they’re served on the site

collections:
  - name: "content"
    label: "Content"
    files:
      - name: "certificates"
        label: "Certificates"
        file: "client/public/content/certificates.json"
        format: "json"
        fields:
          - label: Certificates
            name: certificates
            widget: list
            summary: "{{fields.title}} — {{fields.institution}}"
            fields:
              - { label: Title,        name: title,        widget: string }
              - { label: Institution,  name: institution,  widget: string }
              - { label: Type,         name: type,         widget: string }
              - { label: Description,  name: description,  widget: text }
              - { label: Logo,         name: logo,         widget: image, required: false }
              - { label: Logo Alt,     name: logoAlt,      widget: string, required: false }
